/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fidefyventanas;

/**
 *
 * @author Pau
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form ReproducirCancion
     */
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        LabelContraseña = new javax.swing.JLabel();
        txpContrasena = new javax.swing.JPasswordField();
        lblAceptarCompartirDatos1 = new javax.swing.JLabel();
        lblObligarioPerfil1 = new javax.swing.JLabel();
        lblAceptarTérminos1 = new javax.swing.JLabel();
        checkTérminosDeUso1 = new java.awt.Checkbox();
        checkAceptarCompartirDatos1 = new java.awt.Checkbox();
        lblCrearCuenta = new javax.swing.JLabel();
        lblCualEsTuEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCuenta.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese su nombre de usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 310, 30));

        LabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseña.setText("Cree una contraseña:");
        jPanel1.add(LabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        txpContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txpContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 310, 30));

        lblAceptarCompartirDatos1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAceptarCompartirDatos1.setText("Acepto compartir datos de mi registro  con los proveedores de contenido de Fidefy para fines publicitarios.");
        jPanel1.add(lblAceptarCompartirDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 450, 20));

        lblObligarioPerfil1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        lblObligarioPerfil1.setText("OBLIGATORIO");
        jPanel1.add(lblObligarioPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblAceptarTérminos1.setText("Aceptar los Términos de uso Fidefy");
        jPanel1.add(lblAceptarTérminos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));
        jPanel1.add(checkTérminosDeUso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));
        jPanel1.add(checkAceptarCompartirDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        lblCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearCuenta.setText("Crear Cuenta");
        jPanel1.add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        lblCualEsTuEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCualEsTuEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblCualEsTuEmail.setText("Ingrese su correo electronico :");
        jPanel1.add(lblCualEsTuEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre completo:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 310, 30));
        jPanel1.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 310, 30));

        jLabel4.setText("Términos de uso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(0, 153, 255));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:

        Cuenta cuenta = new Cuenta();

        cuenta.setNombreCompleto(txtNombreCompleto.getText());
        cuenta.setCorreo(txtCorreo.getText());
        cuenta.setUsuario(txtUsuario.getText());
        cuenta.setContrasena(txpContrasena.getText());

        ColeccionUsuarios.add(cuenta);

        try {
            FileOutputStream archivo = new FileOutputStream("Usuarios");
            ObjectOutputStream selializador = new ObjectOutputStream(archivo);
            selializador.writeObject(ColeccionUsuarios);
            selializador.close();
            archivo.close();
            JOptionPane.showMessageDialog(null, "Se agregó el usuario con exito");

        } catch (Exception ex) {
            Logger.getLogger(CrearCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txpContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReproducirCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrearCuenta;
    private java.awt.Checkbox checkAceptarCompartirDatos1;
    private java.awt.Checkbox checkTérminosDeUso1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAceptarCompartirDatos1;
    private javax.swing.JLabel lblAceptarTérminos1;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblCualEsTuEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObligarioPerfil1;
    private javax.swing.JPasswordField txpContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
